services:
  web:
    build: .
    container_name: print-layout-app
    ports:
      - "35124:35124"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development